# SPDX-FileCopyrightText: 2024 Deutsche Telekom AG
#
# SPDX-License-Identifier: Apache-2.0

name: Publish

on:
  push:
    branches: ["main"]

env:
  REGISTRY_URL: ghcr.io
  REGISTRY_USERNAME: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
  REGISTRY_NAMESPACE: michalharakal


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build KMP Project
        run: ./gradlew :composeApp:wasmJsBrowserProductionWebpack

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image
        run: |
          version=$(grep '^version=' $module/gradle.properties | awk -F= '{print $2}')
          docker build -t ghcr.io/michalharakal/ark-view:$version .
          docker push ghcr.io/michalharakal/ark-view:$version
